### ISSUE TITLE
Make it compile on older compiler

### ISSUE THREAD

**Issue by emnh** [Octachron/phantom_algebra#1]
Can you inline map2 again?

And also operators .%(), .%[] and .%{} are not supported on my compiler it seems. Is it possible to use conditional compilation or what compiler do I need to support it?

See https://github.com/emnh/phantom_algebra/commit/5f1735bc3c970a2edea347870ada16defdcd8386 for what I needed to change to make it compile.

**Comment by emnh** [comment]
I think these are the only operators available: http://2ality.com/2017/12/functions-reasonml.html#precedences-and-associativities-of-operators

**Comment by Octachron** [comment]
The extended indexing operators were added in 4.06, I will inline map2 and hide these operators behind some conditional compilation.

**Comment by Octachron** [comment]
I have added some conditional definitions, and the code compiles with OCaml 4.02.3. Could you check that it works for you?

**Comment by emnh** [comment]
Actually I don't know if the reasonml tool chain has the ocaml preprocessor, or maybe if it's a different one. I get the following error:

```bash
FAILED: phantom_algebra/src/interface.mlast
/home/emh/public_html/github/rts-reasonml/node_modules/bs-platform/lib/bsc.exe    -w -30-40+6+7+27+32..39+44+45+101 -bs-suffix -nostdlib -I '/home/emh/public_html/github/rts-reasonml/node_modules/bs-platform/lib/ocaml' -no-alias-deps -color always -c -o phantom_algebra/src/interface.mlast -bs-syntax-only -bs-binary-ast /home/emh/public_html/github/rts-reasonml/phantom_algebra/src/interface.ml
Fatal error: exception File "lexer.mll", line 331, characters 17-23: Assertion failed
```

I might have to build it differently. I just added your directory to my bsconfig.json.

**Comment by emnh** [comment]
I saw you're using something like jbuild? Is it compatible with reason/javascript building?

**Comment by Octachron** [comment]
It seems that the bucklescript compiler's conditionnal compilation reimplementation is not compatible with cppo… Jbuilder works fine with Reason/js_of_ocaml, probably not with Reason/Bucklescript. I am starting to think that the easiest solution here is to split the library in two sublibraries (within this repository): a type-level library with just the interface and type-level functions, and the implementation part.

**Comment by emnh** [comment]
And then you put the indexing operators just in the implementation part? Might work for me yeah.

**Comment by emnh** [comment]
Turns out I want to use the implementation part too, because it's convenient to just call your function implementations with bogus values to inherit their type signatures. But I think I am okay with maintaining a fork where I just remove the indexing operators.

**Comment by emnh** [comment]
I think we can close this, since I am maintaining a fork anyway. By the way, I've tested the phantom algebra on large GLSL programs and it works really well 👍, producing this result http://emh.lart.no/publish/rts-reasonml1/screenshot.jpg .

**Comment by Octachron** [comment]
This looks nice! I got a bit side-tracked by the end of last week, but I should add more convenience functions in the coming weeks; please tell me if it increase your maintenance burdens too much.
